name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --pre jupyterlab
        python -m pip install cookiecutter
    - name: Run tests
      run: |
        which node
        node --version
        mkdir temp
        cd temp
        yarn
        cd /opt/hostedtoolcache/Python/3.7.6/
        yarn add @jupyterlab/coreutils
